export const AppIcons = {
  Xicon: require('../assets/images/Xicon.png'),
  Xwhite: require('../assets/images/Xwhite.png'),
  pic: require('../assets/images/pic.png'),
  pic2: require('../assets/images/pic2.png'),
  pic3: require('../assets/images/pic3.png'),
  pic4: require('../assets/images/pic4.png'),
  pic5: require('../assets/images/pic5.png'),
  pic6: require('../assets/images/pic6.png'),
  pic7: require('../assets/images/pic7.png'),
  pic8: require('../assets/images/pic8.png'),
  pic9: require('../assets/images/pic9.png'),
  pic10: require('../assets/images/pic10.png'),
  pic11: require('../assets/images/pic11.png'),
  pic12: require('../assets/images/pic12.png'),
  pic13: require('../assets/images/pic13.png'),
  pic14: require('../assets/images/pic14.png'),
  pic15: require('../assets/images/pic15.png'),
  pic16: require('../assets/images/pic16.png'),
  image2: require('../assets/images/image2.jpeg'),
  otes: require('../assets/images/otes.jpeg'),
  otesspp: require('../assets/images/otesspp.jpeg'),
  image: require('../assets/images/image.jpeg'),
  image3: require('../assets/images/image3.jpeg'),
  image4: require('../assets/images/image4.jpeg'),
  swim1: require('../assets/images/swim1.jpeg'),
  moh: require('../assets/images/moh.jpeg'),
  me: require('../assets/images/me.jpeg'),
  pes: require('../assets/images/pes.jpeg'),
  pp: require('../assets/images/pp.jpeg'),
  person: require('../assets/images/person.png'),
  check: require('../assets/images/check.png'),
};
AppIcons;
